### ISSUE TITLE
Add support for UWP

### ISSUE THREAD

**Issue by remokeitel** [CommunityToolkit/Datasync#100]
Please add support for UWP. UWP is not deprecated and the only option to develop apps for Xbox.

**Comment by adrianhall** [comment]
Can you provide your target framework moniker for this, please.

**Comment by adrianhall** [comment]
From https://developercommunity.visualstudio.com/t/Add-NET-678-support-to-UWP/1596483

> Thank you for your feedback! Unfortunately, we are not bringing any updates to UWP but we are working on an easy migration > path from UWP to WinUI 3 with Upgrade Assistant. WinUI is the future of UWP that will receive all the new feature and updates. > Have you tried to port your application to WinUI 3? If there are any blockers that prevent you from the migration, we would be > very interested in learning more about it! Feel free to create an issue describing any challenges and we will work on it.
>
> Thanks for your understanding and happy coding!

However, see this article: https://visualstudiomagazine.com/Articles/2024/09/11/Microsofts-Stalled-UWP-Project-Supports-NET-9-as-WinUI-3-Migration-Urged.aspx - so there is hope yet!

This library is based on .NET 8 and uses the newer features of .NET 8.  I won't be back-porting it.  Azure Mobile Apps is still available on NuGet, but won't be getting any future updates.  You are welcome to fork the repository (it's been archived and is MIT licensed) and release a version for yourself.
