### ISSUE TITLE
EndPoint - drops trailing url

### ISSUE THREAD

**Issue by DoyleDavid** [CommunityToolkit/Datasync#108]
My apologies if this is just me not doing the correct thing.  I was using your previous datasync and am moving over to the communitytoolkit version.  

Im using Maui .net with CommunityToolkit.Datasync.Client version 8.0.1

My endpoint hasnt changed since previous version apart from updating to Datasync.Server but i now get an error not found.

When I set the endpoint and I look at the HttpRequest I see its dropping part of my address for the endpoint. eg

I have a web api on iis.

 Endpoint = new Uri("https://svsprod/services/offlineServices/"),

when I check the request on a pull I see:    "https://svsprod/tables/sale/"   
it should be:                                                 https://svsprod/services/offlineServices/tables/sale

Ihave found a work around it but i have to now create an entity for each table to add the extra part.
eg
        optionsBuilder.Entity<sale>(cfg => {
            cfg.ClientName = "sale";
            cfg.Endpoint = new Uri("/services/offlineServices/tables/sale", UriKind.Relative);
});

Thanks. Its an awesome package.

**Comment by RaoulHolzer** [comment]
We have the same issue. I tried to fix is with this code in the class [ExecutableOperation](https://github.com/CommunityToolkit/Datasync/blob/c70c2445fe98e295a73f4e4612073ad9fa63f0b7/src/CommunityToolkit.Datasync.Client/Offline/Operations/ExecutableOperation.cs?plain=1)
` 
         if (baseAddress is { IsAbsoluteUri: true, Segments.Length: > 1 })
          {
              relativeOrAbsoluteUri = new Uri(relativeOrAbsoluteUri.ToString().TrimStart('/'), UriKind.Relative);
              if (baseAddress.ToString()[^1] != '/')
              {
                  baseAddress = new Uri($"{baseAddress}/");
              }
`

But then i see that the test in class [ExecutableOperation_Tests](https://github.com/CommunityToolkit/Datasync/blob/c70c2445fe98e295a73f4e4612073ad9fa63f0b7/tests/CommunityToolkit.Datasync.Client.Test/Offline/Operations/ExecutableOperation_Tests.cs?plain=1 )
 Method MakeAbsoluteUri_Works intended this issue.

**Comment by adrianhall** [comment]
It's designed to work as:

```csharp
Endpoint = new Uri("https://svsprod/services/offlineServices/");
TableEndpoint = new Uri("tables/sale/", UriKind.Relative);
```

... should do what you want.  Note tht the table endpoint is RELATIVE to the Endpoint, so it needs to not have a '/'.

That said, I think the bug is here: https://github.com/CommunityToolkit/Datasync/blob/main/src/CommunityToolkit.Datasync.Client/Offline/Models/OfflineOptions.cs#L55

Can one of you remote the front '/' in that and see if it solves your issues?

**Comment by adrianhall** [comment]
I've posted a PR https://github.com/CommunityToolkit/Datasync/pull/110 which has the suggested fix - feel free to download and check it out.  I'll leave it a week for reviews and intend to merge next MONDAY Oct 1st (I think).

**Comment by DoyleDavid** [comment]
My apologies i got pulled into a different project and now am back on this.  Yes that works well.  sorry for the lateness of the reply. It is now being used and the field and works great. Thanks.
