### ISSUE TITLE
Error when fetching data - The JSON value could not be converted to CommunityToolkit.Datasync.Client.Page

### ISSUE THREAD

**Issue by raymond-dillon** [CommunityToolkit/Datasync#114]
## Describe the bug

Apologies if this is an error in me using the library! 

When retrieving data and adding to a list - 

`            var items = await messageClient.Where(x => x.Id == "142").ToListAsync();
`

I get the error "The JSON value could not be converted to CommunityToolkit.Datasync.Client.Page".

When fetching a single record

` string id = "2";
 ServiceResponse<message> response = await messageClient.GetAsync(id);
 if (response.IsSuccessful && response.HasValue)
 {
     Debug.WriteLine(response.Value);
 }`

It works fine, so I'm assuming my connection to the server is OK. 

Is there a way for ` var items = await messageClient.Where(x => x.Id == "142").ToListAsync();` to return type "message" and not type "page" or how should I handle paging through the data?

## To Reproduce

1.  Make a call to the server using .ToListAsync();

## Expected behavior

A collection of data is returned of type "message" and not "CommunityToolkit.Datasync.Client.Page" or there is a way to convert between the two types.

## What platforms?

Android

* Server:
  * .NET 8
  * SQL Database
  * Azure

* Client:
  * What platform (Android, iOS, Windows, etc.) versions are you running on: Android
  * Does it happen in an emulator / simulator, or only on a real device: Real Device
  * Version of dotnet being used to compile: 8.
  * .NET Runtime Environment (WPF, UWP, WinUI3, MAUI, etc.): MAUI
  * Datsync Toolkit NuGet versions: 8.0.1

**Comment by adrianhall** [comment]
I'll need a lot more to go on here.  I have explicit tests for this scenario.

What does your client setup look like?
What does your server setup look like?
Can you write a unit test that replicates the error?

**Comment by raymond-dillon** [comment]
I'll try and repo with a basic setup and a unit test to see if it's something I'm doing wrong.

Will get back to you ASAP.

________________________________
