### ISSUE TITLE
DateTimeOffset.Parse issue when items go back and forth between server and maui client

### ISSUE THREAD

**Issue by FrederikFBrandt** [CommunityToolkit/Datasync#115]
## Describe the bug

String '2024-09-25T22.06.59.945Z' was not recognized as a valid DateTime. at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles, TimeSpan& offset) at System.DateTimeOffset.Parse(String input) at CommunityToolkit.Datasync.Server.Abstractions.Json.DateTimeOffsetConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)

If I populate my item in the MAUI client like:
DateTimeOffset? CreatedAt = DateTimeOffset.UtcNow;

The server will respond with the error above.

If the server populates the CreatedAt, it works fine. But when I then make a change to the same item and try to synchronize the database with the server, sending back the same object, the server again complains about the string not being parsed during json deserialization.

## Expected behavior

Json conversion happens effortlessly or Im able to setup my own jsonserializer options

## What platforms?

* Server:
  .NET Core 8

* Client:
  * I run it on .NET MAUI Android

**Comment by FrederikFBrandt** [comment]
The same thing happens if the UpdatedAt value is updated when the client tries to send an updated entity back to the server.

**Comment by FrederikFBrandt** [comment]
Yes, I got that. I am not touching UpdatedAt clientside. I am passing an empty UpdatedAt from the client to the server, this works. When the object comes back from the server with the UpdatedAt, this also works. When the object is then changed clientside, and the client tries to pass the object to the server, I get the serialization error. My theory is that the client isn't trying to alter the UpdatedAt, it is simply trying to send the existing UpdatedAt value to the server, and that causes the serialization issue. I'm in Denmark, so it would be Danish locale

**Comment by adrianhall** [comment]
TODO:
* Add list of locales to test as a MemberData property in Abstractions.Test/Json/SerializerTests.cs with initial set of locales being "fr-FR", "da-DA", and "en-US".
* Add locale specific tester
* Update tests in Json to use locale specific tester.
* Any corrections to the Json converters in CT.D.Server.Abstractions needed as a result of tests failing.
