### ISSUE TITLE
Swagger unable to document parameters on POST verb

### ISSUE THREAD

**Issue by nitech** [CommunityToolkit/Datasync#118]
I set up a test implementation of CommunityToolkit.Datasync.Server and inspected the Swagger UI interface. I notice that GET, PUT and DELETE both document and work fine, but POST does not let me type the values Name and Operational of the Ship entity:

```c#
public class Ship : LiteDbTableData
{
    [Required]
    public string Name { get; set; } = string.Empty;
    public bool Operational { get; set; } = false;
}
```

![image](https://github.com/user-attachments/assets/d20c37d1-67d5-45eb-a917-e694a06ff406)

I tested the POST method separately via Postman, and see it works fine. It seems Swagger is unable to auto generate the parameters because the Controller implements the TableController class of `CommunityToolkit.Datasync.Server`

```c#
[Route("tables/[controller]")]
public class ShipController : TableController<Ship>
{
    public ShipController(LiteDatabase db) : base(new LiteDbRepository<Ship>(db, "ships"))
    {
    }
}
```

I really would like to re-use the API for both the Avalonia Client and the Admin Website. As it stands I can do this, but the Swagger UI does not properly document the POST method.

When I POST via PostMan, I am able to invoke the POST verb, so I am quite confident the problem is introduced by the TableController<T> somehow. Is there a way to make the Swagger UI document properly?

**Comment by nitech** [comment]
Using nswag
See https://github.com/nitech/SevenShipsServer.Issue118
Thanks 👍

**Comment by adrianhall** [comment]
RCA - the operation.Consumes is not being set by NSwag for either PUT or POST operations.

**Comment by adrianhall** [comment]
Hi @nitech - I've created a PR for fixing the problem you reported here (it was also present on the PUT verb and dealt with polymorphism and inheritence).

Can you please try out the new NSwag library code (you'll have to download the PR code and compile it) - let me know if it fixes the problem.

**Comment by nitech** [comment]
Hi @adrianhall, I can confirm it works now. And you were correct, it was also an issue with the PUT verb. 

Well done and thanks for your effort. 

![image](https://github.com/user-attachments/assets/10be1f0e-119b-479e-8a42-e8a7d5f182f1)
