### ISSUE TITLE
How to realize batch data clear and resync

### ISSUE THREAD

**Issue by ks3140** [CommunityToolkit/Datasync#129]
We recognize that “azure-mobile-apps” (*1) will be unsupported on August 2, 2024, and although it can be used, it will not be updated, so the use of “CommunityToolkitDatasync” (*2) instead of “azure-mobile-apps” is required to keep up with updates. is necessary to keep up with the updates.
*1 https://github.com/Azure/azure-mobile-apps
*2 https://github.com/CommunityToolkit/Datasync
 
Currently, we are using “azure-mobile-apps” PurgeItemsAsync() (*3) with PurgeOptions TimestampUpdatePolicy.UpdateToEpoch (reset delta token) for data synchronization and bulk UpdateToEpoch (resetting the delta token) is used to delete the data in bulk.
After that, data synchronization is performed to achieve bulk data clearing and resynchronization (after all data is deleted on the app side, data in Azure CosmosDB is not deleted, and data in Azure Cosmos DB is acquired (synchronized) on the app side).
*3 https://learn.microsoft.com/ja-jp/previous-versions/azure/developer/mobile-apps/azure-mobile-apps/howto/client/dotnet#advanced- TOPICS
 
I checked the CommunityToolkitDatasync source, but PurgeItemsAsync() does not exist, and I cannot find any function equivalent to deleting data using PurgeOptions.
Could you please tell us how to realize batch data clear and resync using CommunityToolkitDatasync (after deleting all data on the app side, the data in Azure CosmosDB is not deleted and the data in Azure Cosmos DB is acquired (synchronized) on the app side).

Thank you.

**Comment by richard-einfinity** [comment]
All the entity sets are exposed on the base OfflineDbContext. 

Run ExecuteDelete on all the sets including DatasyncOperationsQueue and DatasyncDeltaTokens with no parameters.

This should leave you with an empty database and as ExecuteDelete bypasses the change tracker no additional options should be added to the queues,

**Comment by adrianhall** [comment]
What @richard-einfinity said - you now have direct access to datasets representing the operations queue and the delta token store - you can update as you see fit.  You can write something akin to the following:

```csharp
using (AppDbContext ctx = GetContext())
{
  ctx.DatasyncDeltaTokens.ExecuteDelete();
  ctx.DatasyncOperationsQueue.ExecuteDelete();
  // Repeat for each other table to clear - you are in a bad state at this point

  // Save changes - consider async here; ensures the changes are not added to the queue
  ctx.SaveChanges(acceptAllChangesOnSuccess: false, addToQueue: false);
}
```

Now you can do your re-sync.
