### ISSUE TITLE
Online Operations Guide 

### ISSUE THREAD

**Issue by atexinspect** [CommunityToolkit/Datasync#138]
Any chance of a valid link for Online Operations Guide?

https://communitytoolkit.github.io/Datasync/in-depth/client/online-operations.md

Thanks 
Paul.

**Comment by adrianhall** [comment]
Right now - it's https://communitytoolkit.github.io/Datasync/in-depth/client/oneline-operations/index.html

But that's wrong - I'll get that fixed (hopefully today!)
