### ISSUE TITLE
Dependency on Microsoft.EntityFrameworkCore, Version=8.0.11.0

### ISSUE THREAD

**Issue by SorenBech2** [CommunityToolkit/Datasync#164]
When trying to load a DataSync client app in MAUI using .NET 9 including EntityFrameWork 9 an exception is thrown:

System.TypeLoadException: 'Could not resolve type with token 010001b7 from typeref (expected class 'Microsoft.EntityFrameworkCore.Metadata.Internal.AdHocMapper' in assembly 'Microsoft.EntityFrameworkCore, Version=8.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60')'

If Nuget package Microsoft.EntityFrameworkCore Version 8.0.11 is used insted of version 9.0.0, no issue.

It appears to be OfflineDbContext which throws this exception when loaded, but I can not pin point the issue closer than this. No issue building the app.

Issue appears on Android, IOS & Windows.
Have only tested on real devices.
.NET 9
MAUI 9.0.12
CommunityToolkit.Datasync.Client v. 8.0.4

**Comment by adrianhall** [comment]
This is correct.  CommunityToolkit.Datasync.Client depends on EntityFrameworkCore 8.x.

I will be working on a 9.x branch in the near future.
