### ISSUE TITLE
MAUI based Todo App Sample

### ISSUE THREAD

**Issue by adrianhall** [CommunityToolkit/Datasync#22]
Must use the Sample.Datasync.Server and support the usual flow for tutorials (remote, auth, offline sync)

**Comment by powerdude** [comment]
it would be nice if the app was a little more complicated than the simple Todo app.  At least something with a couple entities that have a relationship.

**Comment by adrianhall** [comment]
I completely agree with you; I'm happy to take a PR for a more fully featured sample with relationships - as long as it comes with documentation (there is a samples section).
