### ISSUE TITLE
OfflineClientEntity class does not exists

### ISSUE THREAD

**Issue by pirras-torres** [CommunityToolkit/Datasync#60]
Class OfflineClientEntity does not exists

![image](https://github.com/user-attachments/assets/cef22cfa-1244-4c86-b000-f26eabe865be)

Compile WinUI example

**Comment by adrianhall** [comment]
The examples don't work yet due to multiple re-works.  I appreciate the reminder, though :-)

**Comment by adrianhall** [comment]
WinUI sample has been updated.  I've also included comments on what needs to change to enable it for offline usage.  Tutorial coming with the docs.
