### ISSUE TITLE
[Feature request] Using enum comparisons in queries

### ISSUE THREAD

**Issue by hansmbakker** [CommunityToolkit/Datasync#61]
**Is your feature request related to a problem? Please describe.**
The archived azure-mobile-apps sdk did not support enums in queries (especially client-side).

**Describe the solution you'd like**
Support for queries that use enums in `Where` filters

```csharp
var query = dataSyncClient.GetTable<InspectionSyncModel>()
    .Where(x => x.Status == InspectionStatusSyncModel.Unassigned);

var count = await query.LongCountAsync();
```

In the old SDK, that syntax was supported but it returned zero results for us.

**Describe alternatives you've considered**
Doing a string-based comparison in the `Where` query - this was the workaround for the old sdk.

```csharp
var query = dataSyncClient.GetTable<InspectionSyncModel>()
    .Where(x => x.Status.ToString().Equals(InspectionStatusSyncModel.Unassigned.ToString(), StringComparison.OrdinalIgnoreCase));

var count = await query.LongCountAsync();
```
**Additional context**
Maybe using EF Core client-side will support this out-of-the-box?

**Comment by adrianhall** [comment]
Huh - I thought I had tests for that.  In any case, I have a slew of enums in the test data, so it won't be hard to add tests for this in the future.  I'll take a look.  May have to wait for 8.0.1 though (even though I am adding it to the 8.0.0 milestone for now).

**Comment by adrianhall** [comment]
See the integration tests added.  There are several online and pull/push offline tests using enums now.
