### ISSUE TITLE
Migration From Microsoft.Azure.Mobile.Client version 2.03

### ISSUE THREAD

**Issue by ricardocesarcara** [CommunityToolkit/Datasync#64]
Hi Adrianhall, I really appreciate your effort.
Just one question, I have an application that I intend to migrate, both the server and the application still use Microsoft.Azure.Mobile.Server and Microsoft.Azure.Mobile.Client version 2.03 which is very old. Do you think I can migrate to DataSync without having to change database structures?

tanks.

**Comment by adrianhall** [comment]
On the server side, you should have no issues.

On the client side, you will need a new database structure.
