### ISSUE TITLE
Avalonia UI base sample

### ISSUE THREAD

**Issue by adrianhall** [CommunityToolkit/Datasync#82]
Do the TodoApp for Avalonia UI

**Comment by nitech** [comment]
https://communitytoolkit.github.io/Datasync/ has an URL to the Avalonia UI sample - but it returns a 404 on https://communitytoolkit.github.io/Datasync/samples/todoapp/avalonia.md

**Comment by adrianhall** [comment]
The docs / sample for Avalonia and Uno are not yet available.  It's a good point though - I should remove the link until they are available.

**Comment by nitech** [comment]
Thanks @adrianhall. May I ask - knowing little of the history of Datasync. I understand it used to be called Azure Mobile Apps and has been donated (?) to the CommunityToolkit. Correct? If I am correct, does this mean that Datasync is a mature package and just continues the work of Azure Mobile Apps?

**Comment by adrianhall** [comment]
See #159
