### ISSUE TITLE
[Client] Unable to implement online operations as per documentation (DatasyncServiceClient<TEntity>)

### ISSUE THREAD

**Issue by Nicmanthecodeman** [CommunityToolkit/Datasync#99]
## Describe the bug

I cannot implement online operations from the client after following the [documentation](https://communitytoolkit.github.io/Datasync/in-depth/client/oneline-operations/index.html#create-a-datasync-service-client). More specifically, I cannot create a DatasyncServiceClient since its access modifier is marked as internal. 

## To Reproduce

1. Go to the [documentation](https://communitytoolkit.github.io/Datasync/in-depth/client/oneline-operations/index.html#creating-a-http-client-factory) to implement online operations.
2. Follow the steps `Creating a Http Client Factory` and `Create a Datasync Service Client`
3. See the error as shown in the image below.

## Expected behavior

The DatasyncServiceClient class should be able to be instantiated. If this should not be the case, ammend the documentation in order to provide clear guidance regarding the implementation of online operations.

## What platforms?

* Server:
  * .NET 8
  * CommunityToolkit.Datasync.Server --version 8.0.0
  * CommunityToolkit.Datasync.Server.EntityFrameworkCore --version 8.0.0
  * MS SQL
  * Windows (Local)

* Client:
  * Windows
  * Local device
  * .NET 8
  * MAUI
  * CommunityToolkit.Datasync.Client --version 8.0.0

## Screenshots

![image](https://github.com/user-attachments/assets/d38f18f9-0017-42fe-9818-6b82fc26311b)

## Additional context

N/A

**Comment by adrianhall** [comment]
Ooops :-)  Easy fix - will be in 8.0.1 (which I'm hoping to get released today)

**Comment by raymond-dillon** [comment]
Hi @adrianhall - thanks for the fix. I'm converting a Xamarin Forms app to .NET MAUI and attempting to migrate from Azure Mobile Client to DataSync and I was wondering where the best place to ask questions are? I'm not sure if the issues I'm facing are bugs or not setting things up correctly.

**Comment by adrianhall** [comment]
Hi @raymond-dillon - a quick note that I do not generally go back to closed issues.  A closed issue is perhaps the worst place to ask questions.

The discussions area is the best place to ask questions.  If I determine its a bug, then I can turn it into an issue directly.  I'm also happy to have a discussion as an open issue.
